### ISSUE TITLE
New Outlaw gun?

### ISSUE THREAD

**Issue by DyonR** [pwall2222/NOWT#3]
Hi, do you have plans to add support for the new Outlaw gun and the 4th spray?  
The Discord link in the README.md is still from "Soneliem/WAIUA", else I would've reached out in that way.

**Comment by ajilidali** [comment]
I opened a pull request for outlaw. #4

**Comment by ajilidali** [comment]
UPDATE : I actually did the changes, althought I didn't use Visual Studios own graphical thing, this is what I got :
![image](https://github.com/pwall2222/NOWT/assets/40182073/eae334a6-3ec2-40ea-b06e-d2ab0ba25c12)
VS gives a weird preview I don't know why and I'm sure there's probably a better way to do this but it didn't come to mind.
![image](https://github.com/pwall2222/NOWT/assets/40182073/d09db339-aeaa-4d98-a6c2-9ae666e9ed6b)

**Comment by pwall2222** [comment]
> Hi, do you have plans to add support for the new Outlaw gun and the 4th spray? The Discord link in the README.md is still from "Soneliem/WAIUA", else I would've reached out in that way.

Also I prefer issue tracking on GitHub, but the I still have to update the ReadMe.

**Comment by pwall2222** [comment]
The OutLaw has been added in #4 I will make another issue for the 4th spray.
