### ISSUE TITLE
Feature: Clickable map

### ISSUE THREAD

**Issue by Mylloon** [pwall2222/NOWT#7]
May be cool to make the map clickable

On click: it open the map with all the names

**Comment by pwall2222** [comment]
Can you elaborate? @Mylloon

**Comment by pwall2222** [comment]
It's a neat, over complicated and yeah not all that useful idea.
It may also contain location and useful links.

Personally I have no interest in implementing this feature, I will accept PRs tho!
I will close this issue for now.
