### ISSUE TITLE
Tracker.gg links gone?

### ISSUE THREAD

**Issue by DyonR** [pwall2222/NOWT#8]
For something like a week, names are not hyperlinked anymore to open someone's tracker.gg profile.  
Normally, if their tracker.gg was public, you could click on the name to open the tracker.gg page.
Right now, the names are ALWAYS grayed out (even mine, which is public)
In the picture below I've censored the names, but that is where you would normally be able to click on them.  

![image](https://github.com/pwall2222/NOWT/assets/16341409/d0f96875-e32e-44aa-85d7-1359f86f6b1f)

**Comment by pwall2222** [comment]
@DyonR Could you provide some logs?
They are located in `%LocalAppData%\NOWT\logs\` with the names:
`log{date}.txt`

You can censor the tracker.gg URLs if they appear.

**Comment by pwall2222** [comment]
Well, I already find the issue, CloudFlare was giving us 403, for not using a "correct" User-Agent.

**Comment by DyonR** [comment]
Sadly not fixed. Issue still persists. Thanks for the quick reply tho :)

**Comment by DyonR** [comment]
May it be because `userAgentTrickery` is set to false?  
https://github.com/pwall2222/NOWT/blob/877ff39b830528eafc1d2f2d292616df5914e349/NOWT/Helpers/Login.cs#L176

**Comment by pwall2222** [comment]
> Sadly not fixed. Issue still persists. Thanks for the quick reply tho :)

Should be fixed in v1.3.3
